export enum ChessTitle {
  FIDE_CANDIDATE_MASTER = 'CANDIDATE_MASTER',
  WOMAN_FIDE_CANDIDATE_MASTER = 'WOMAN_FIDE_CANDIDATE_MASTER',
  FIDE_MASTER = 'FIDE_MASTER',
  WOMAN_FIDE_MASTER = 'WOMAN_FIDE_MASTER',
  INTERNATIONAL_MASTER = 'INTERNATIONAL_MASTER',
  WOMAN_INTERNATIONAL_MASTER = 'WOMAN_INTERNATIONAL_MASTER',
  GRANDMASTER = 'GRANDMASTER',
  WOMAN_GRANDMASTER = 'WOMAN_GRANDMASTER',
  NO_TITLE = 'NO_TITLE'
}

export const chessTitleToLabelMapping: Record<ChessTitle, string> = {
  [ChessTitle.FIDE_CANDIDATE_MASTER]: 'CM',
  [ChessTitle.WOMAN_FIDE_CANDIDATE_MASTER]: 'WCM',
  [ChessTitle.FIDE_MASTER]: 'FM',
  [ChessTitle.WOMAN_FIDE_MASTER]: 'WFM',
  [ChessTitle.INTERNATIONAL_MASTER]: 'IM',
  [ChessTitle.WOMAN_INTERNATIONAL_MASTER]: 'WIM',
  [ChessTitle.GRANDMASTER]: 'GM',
  [ChessTitle.WOMAN_GRANDMASTER]: 'WGM',
  [ChessTitle.NO_TITLE]: 'No title'
};
